// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var HighlightJs = require("highlight.js");

var HighlightValue = {};

var Highlight = {};

var removeLanguagePrefix = ((str) => str.replace('language-', ''));

function highlight(code, language) {
  return HighlightJs.highlightAuto(code, [removeLanguagePrefix(language)]).value;
}

exports.HighlightValue = HighlightValue;
exports.Highlight = Highlight;
exports.removeLanguagePrefix = removeLanguagePrefix;
exports.highlight = highlight;
/* highlight.js Not a pure module */
