// Generated by BUCKLESCRIPT VERSION 5.0.1, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var HighlightJs = require("highlight.js");

var HighlightValue = /* module */[];

var Highlight = /* module */[];

var removeLanguagePrefix = ((str) => str.replace('language-', ''));

function highlight(code, language) {
  return HighlightJs.highlightAuto(code, /* array */[Curry._1(removeLanguagePrefix, language)]).value;
}

exports.HighlightValue = HighlightValue;
exports.Highlight = Highlight;
exports.removeLanguagePrefix = removeLanguagePrefix;
exports.highlight = highlight;
/* removeLanguagePrefix Not a pure module */
