// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function make(name, iterations) {
  return {
          iterations: iterations,
          name: name
        };
}

var State = {
  make: make
};

function ofType(actionType) {
  return {
          kind: actionType
        };
}

var Action = {
  ofType: ofType
};

var initialState = {
  iterations: 0,
  name: "world"
};

var mutatedState = {
  contents: initialState
};

function unref(refState) {
  return refState.contents;
}

function updateState(previous, action) {
  mutatedState.contents = {
    iterations: previous.iterations + 1 | 0,
    name: "updates"
  };
  return mutatedState.contents;
}

var refRoot = {
  contents: undefined
};

var render = ((state, root) => root`<div onclick=${onClicked}>
    Hello, ${state.name} ${state.iterations}
  </div>`);

function dispatch(action) {
  var root = refRoot.contents;
  var state = updateState(mutatedState.contents, action);
  if (root !== undefined) {
    render(state, root);
  }
  
}

function onClicked(param) {
  return dispatch({
              kind: /* Update */0
            });
}

function main(param) {
  var renderer = hyperHTML.bind(document.getElementById("root"));
  refRoot.contents = renderer;
  render(initialState, renderer);
  
}

window.onload=main
;

exports.State = State;
exports.Action = Action;
exports.initialState = initialState;
exports.mutatedState = mutatedState;
exports.unref = unref;
exports.updateState = updateState;
exports.refRoot = refRoot;
exports.render = render;
exports.dispatch = dispatch;
exports.onClicked = onClicked;
exports.main = main;
/*  Not a pure module */
