// Generated by BUCKLESCRIPT VERSION 5.0.1, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var ArrayLabels = require("bs-platform/lib/js/arrayLabels.js");

var Fs$1 = /* module */[];

var Path = /* module */[];

function readFile(filename) {
  var exists = Fs.existsSync(filename);
  if (exists) {
    var isFile = Fs.statSync(filename).isFile();
    if (isFile) {
      return Fs.readFileSync(filename, "utf8");
    } else {
      return undefined;
    }
  }
  
}

function readDir(dir) {
  var match = Fs.existsSync(dir);
  if (match) {
    var isFile = Fs.statSync(dir).isFile();
    if (isFile) {
      return /* [] */0;
    } else {
      return ArrayLabels.to_list(Fs.readdirSync(dir));
    }
  } else {
    return /* [] */0;
  }
}

exports.Fs = Fs$1;
exports.Path = Path;
exports.readFile = readFile;
exports.readDir = readDir;
/* fs Not a pure module */
