// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var ArrayLabels = require("rescript/lib/js/arrayLabels.js");

var Fs$1 = {};

var Path = {};

function readFile(filename) {
  var exists = Fs.existsSync(filename);
  if (!exists) {
    return ;
  }
  var isFile = Fs.statSync(filename).isFile();
  if (isFile) {
    return Fs.readFileSync(filename, "utf8");
  }
  
}

function readDir(dir) {
  if (!Fs.existsSync(dir)) {
    return /* [] */0;
  }
  var isFile = Fs.statSync(dir).isFile();
  if (isFile) {
    return /* [] */0;
  } else {
    return ArrayLabels.to_list(Fs.readdirSync(dir));
  }
}

exports.Fs = Fs$1;
exports.Path = Path;
exports.readFile = readFile;
exports.readDir = readDir;
/* fs Not a pure module */
