// Generated by BUCKLESCRIPT VERSION 5.0.1, PLEASE EDIT WITH CARE
'use strict';


var md = (require('markdown-it')({
    html:false
}).use(
    require('markdown-it-footnote')
));

var markdown = ((input) => md.render(input));

exports.md = md;
exports.markdown = markdown;
/* md Not a pure module */
