// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var prism = (require("prismjs"));

((require("prismjs/components/")()));

function removeLanguagePrefix(str) {
  return str.replace("language-", "");
}

function highlight(code, language) {
  var doHighlight = ((code, language) => prism.highlight(code, prism.languages[language], language));
  return doHighlight(code, language.replace("language-", ""));
}

exports.prism = prism;
exports.removeLanguagePrefix = removeLanguagePrefix;
exports.highlight = highlight;
/* prism Not a pure module */
