// Generated by BUCKLESCRIPT VERSION 5.0.1, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

var prism = (require("prismjs"));

((require("prismjs/components/")()));

function removeLanguagePrefix(str) {
  return str.replace("language-", "");
}

function highlight(code, language) {
  var doHighlight = (
        (code, language) => prism.highlight(code, prism.languages[language], language)
    );
  return Curry._2(doHighlight, code, language.replace("language-", ""));
}

exports.prism = prism;
exports.removeLanguagePrefix = removeLanguagePrefix;
exports.highlight = highlight;
/* prism Not a pure module */
